name: Run Cypress Tests
on: push
jobs:
  run-cypress:
     name: Run Cypress
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Cypress run
         uses: cypress-io/github-action@v2
         with:
           build: yarn run build
           start: yarn start
           wait-on: "http://localhost:3000"