name: Run Cypress Tests
on: push
jobs:
  run_cypress:
     name: Run Cypress
     runs-on: ubuntu-latest
     timeout-minutes: 20
     steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Cypress run
         uses: cypress-io/github-action@v2
         with:
           dev: yarn dev
           config-file: cypress.json
           wait-on: "http://localhost:3000"
           wait-on-timeout: 300
           browser: chrome
           headless: true
